<a href="https://colab.research.google.com/github/mariuszkr33/dw_matrix/blob/master/Pandas191.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


np.__version__

'1.18.5'

In [ ]:
data = {
    'size' : ['XL', 'L', 'M', 'L', 'M'],
    'color' : ['red', 'green', 'blue', 'green', 'red'],
    'gender' : ['female', 'male', 'male', 'female', 'female'],
    'price' : [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight' : [500, 450, 300, 380, 410],
    'bought' : ['yes', 'no' , 'yes', 'no', 'yes']
}

In [ ]:
df = pd.DataFrame(data)
df

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


In [ ]:
for col in ['size', 'color', 'gender', 'bought']:
  df[col] = df[col].astype('category')

df['weight']=df['weight'].astype('float')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 628.0 bytes


In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder() ## tworzymy instancję klasy
df['bought'] = le.fit_transform(df['bought'])
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

In [ ]:
df['bought'] = le.inverse_transform(df['bought'])
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

In [ ]:
df['bought'] = df['bought'].astype('category')
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 628.0 bytes


In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse=False)
encoder.fit_transform(df[['size']])


array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
encoder = OneHotEncoder(sparse=False, drop='first')
encoder.fit_transform(df[['size']])

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [ ]:
pd.get_dummies(df)



price  weight  size_L  ...  gender_male  bought_no  bought_yes
0  199.0   500.0       0  ...            0          0           1
1   89.0   450.0       1  ...            1          1           0
2   99.0   300.0       0  ...            1          0           1
3  129.0   380.0       1  ...            0          1           0
4   79.0   410.0       0  ...            0          0           1

[5 rows x 12 columns]

In [ ]:
pd.get_dummies(df, drop_first=True)

price  weight  size_M  ...  color_red  gender_male  bought_yes
0  199.0   500.0       0  ...          1            0           1
1   89.0   450.0       0  ...          0            1           0
2   99.0   300.0       1  ...          0            1           1
3  129.0   380.0       0  ...          0            0           0
4   79.0   410.0       1  ...          1            0           1

[5 rows x 8 columns]

In [ ]:
pd.get_dummies(df, columns=['size'], drop_first=True)

color  gender  price  weight bought  size_M  size_XL
0    red  female  199.0   500.0    yes       0        1
1  green    male   89.0   450.0     no       0        0
2   blue    male   99.0   300.0    yes       1        0
3  green  female  129.0   380.0     no       0        0
4    red  female   79.0   410.0    yes       1        0

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit_transform(df[['weight']])

array([[ 1.3660019 ],
       [ 0.62360956],
       [-1.60356745],
       [-0.41573971],
       [ 0.02969569]])

In [ ]:
df = pd.DataFrame(data)
df

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [ ]:
df_prep = df.copy()

encoder = LabelEncoder() ## tworzymy instancję klasy
df_prep['bought'] = encoder.fit_transform(df_prep['bought'])

scaler = StandardScaler()
df_prep[['weight', 'price']] = scaler.fit_transform(df_prep[['weight', 'price']])

df_prep = pd.get_dummies(df_prep, drop_first=True)

df_prep


price    weight  bought  ...  color_green  color_red  gender_male
0  1.845062  1.366002       1  ...            0          1            0
1 -0.691898  0.623610       0  ...            1          0            1
2 -0.461266 -1.603567       1  ...            0          0            1
3  0.230633 -0.415740       0  ...            1          0            0
4 -0.922531  0.029696       1  ...            0          1            0

[5 rows x 8 columns]

In [ ]:
 data = df_prep.copy()
 target = data.pop('bought')
 

In [ ]:
data.head()

price    weight  size_M  size_XL  color_green  color_red  gender_male
0  1.845062  1.366002       0        1            0          1            0
1 -0.691898  0.623610       0        0            1          0            1
2 -0.461266 -1.603567       1        0            0          0            1
3  0.230633 -0.415740       0        0            1          0            0
4 -0.922531  0.029696       1        0            0          1            0

In [ ]:
target.head()

0    1
1    0
2    1
3    0
4    1
Name: bought, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2)

print(f'X_train shape: {X_train.shape}')
print(f'X_test shape: {X_test.shape}')
print(f'y_train shape: {y_train.shape}')
print(f'y_test shape: {y_test.shape}')

X_train shape: (4, 7)
X_test shape: (1, 7)
y_train shape: (4,)
y_test shape: (1,)


In [ ]:
X = pd.concat([X_train,X_test])
X

price    weight  size_M  size_XL  color_green  color_red  gender_male
3  0.230633 -0.415740       0        0            1          0            0
4 -0.922531  0.029696       1        0            0          1            0
2 -0.461266 -1.603567       1        0            0          0            1
0  1.845062  1.366002       0        1            0          1            0
1 -0.691898  0.623610       0        0            1          0            1

In [ ]:
y = pd.concat([y_train,y_test])
y

3    0
4    1
2    1
0    1
1    0
Name: bought, dtype: int64

In [ ]:
pd.concat([X,y], axis=1)

price    weight  size_M  ...  color_red  gender_male  bought
3  0.230633 -0.415740       0  ...          0            0       0
4 -0.922531  0.029696       1  ...          1            0       1
2 -0.461266 -1.603567       1  ...          0            1       1
0  1.845062  1.366002       0  ...          1            0       1
1 -0.691898  0.623610       0  ...          0            1       0

[5 rows x 8 columns]