<a href="https://colab.research.google.com/github/mariuszkr33/dw_matrix/blob/master/ScikitLearn34.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


df = pd.DataFrame({'years': [1, 2, 3, 4, 5, 6],
                   'salary': [4000, 4250, 4500, 4750, 5000, 5250]})
df

years  salary
0      1    4000
1      2    4250
2      3    4500
3      4    4750
4      5    5000
5      6    5250

In [ ]:
X1 = df['years'].values
Y = df['salary'].values
X1

array([1, 2, 3, 4, 5, 6])

In [ ]:
Y

array([4000, 4250, 4500, 4750, 5000, 5250])

In [ ]:
m = len(df)
m

6

In [ ]:
X1 = X1.reshape(m, 1)
X1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
bias = np.ones((m, 1))
bias

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
X = np.append(bias, X1, axis=1)
X

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 6.]])

In [ ]:
coefs = np.dot(np.linalg.inv(np.dot(X.T, X)), np.dot(X.T, Y))
coefs

array([3750.,  250.])

In [ ]:
print(f'Linear regression: {coefs[0]:.2f} + {coefs[1]:.2f}x')

Linear regression: 3750.00 + 250.00x


In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(df[['years']], df[['salary']])

print(f'Linear regression: {model.intercept_[0]:.2f} + {model.coef_[0][0]:.2f}x')

Linear regression: 3750.00 + 250.00x


In [ ]:
model.intercept_[0]

3750.0

In [ ]:
model.coef_[0][0]

250.0

In [ ]:
model.intercept_

array([3750.])

In [ ]:
model.coef_

array([[250.]])

In [ ]:
print(f'{model.score(df['years'], df['salary']):.4f}')

SyntaxError: ignored